osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- brew update
- brew install carthage
- brew outdated carthage || brew upgrade carthage
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
before_script:
- carthage bootstrap
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/com.awareframework.ios.sensor.core.xcworkspace
  -scheme com.awareframework.ios.sensor.core-Example -sdk iphonesimulator12.1 -destination
  OS=12.1,name="iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -allowProvisioningUpdates
  | XCPRETTY
before_deploy:
- carthage build --archive
deploy:
  provider: script
  script: "./scripts/release.sh"
  skip_cleanup: true
  on:
    tags: true
after_success:
- echo 'success!'
env:
  global:
  - secure: Op4GxN+B6fMz7LUlF0tBVN9U9mBTNlv+51htvTzbRpZe1Wot4i+MiW8IdeCJ/N0ycdqFwk7kMKluo4DHZjEou8mnT+JIff5zyYDS+JKn/JRW98HhYsZ/wwWCdIHLFhxomXE8BYiE/zNDjUimcz94pM0DQr01jgows57V7UuQXc8fyTU7+A48sRUX3Q8Ug8NLkG76Ofk+fNsMtaYwwu4SD6FArZnv5vy5mLqU8VGMqRDKSe1Ue7XUvOmqvZWjZqgZ8Ks7YaH6xJHiFzIJ0aJiONIUt+rLZsYYuTbH3fDmvunSXv8cv+iQlN0b125trdkVXA5Y8w6pUEwofyXUfb9X7buOViTc62+v3snzjEKc199JOG0cUOfO3PChf+4zJ6uE1JUi3rpzT8VKgvC0ATHxsgMa+V6iu/jvLQgk3K2AD5OTY+/QFQdW6bxrDuS9HJzTq/++C8AUl7vhEZ8EorFdqRnE/kS/WO0lsn7BMc1IWV1IznTaGCmlKcZMumk1rD9+FB3mXAS62x3/gOIxlS8F1vpVlPNEhxIZP1JS0XFhXY6H9O/EvCKr5Gwen+x8xRRNPXdaWUzBbsWjl26F7TJJtZbHxNY5Dwz6Mh9hVaBmDrjpqk4Jpk2wlyqXyUJPkGtKokBvtP4MqdyZSa11gSzIdXFKbH3OA7tuIW52UHyAZJI=
notifications:
  slack:
    secure: MUpMy4a/P/5cUq1v+4t6z8ZR45bAhT+cU1xokCSit9MO81Lp5VQxoyi/34XXU72StMdnwTUeGYlTaaed7ocSWjA3y8Ze31HbxxkkbfGsJb94y+SV+O3iXugzi2dYo96zVCcPbbn4LjBdCCqhyXK9A3FhzxtEoe55X1A4+kjjxCCrsnB8ED+Wu4zCqy6FNrhNw0yesqOOX7Foo2Kf6CPE4LX3HcetRJ60dmzxbbVkDByDVPYWKfpFeMqV0WkGGZqzKGpuOTqUmh3ciSYGmwTyLQ+l4FSFtJS+jDXdVHvOr2wPjABbGmhzPEm2IM3g4y+Oo+3QEFIhQBhMd14x9wacVVIRi6LD3yP98DBHtGuSB2+dyxoajJ32Y7s7n5hFCgq6STMZGJxny4VUaJzN1IX9Df9JHs/lWV0s9yiiA5kfr0byE9cCF27WtJ7nOiNR21tjuZJ7tyJKJjWT4uqxVr1Po3usVMnRQmQ42KI33PKA3kTxC7UGbX+oxF+qrPFFy3i+12DE9MwJ3UHnABIw0C9caioUbr+CEDEXBx/CDOgZC1Xz2fizdKagLX9j3IDyCMacIpX23AOgL9wD3P8X7qVrIgoB0wpkoX42Ev2WVTrEhm7PMT/3ToziB2OGwqkbZBS9TkRad7wWXdi7iSMTmgzkb30tINj3mgdzE8FW+JUkN8A=
